### ISSUE TITLE
Vue directive "Element value was changed outside of mask"

### ISSUE THREAD

**Issue by yudhy101** [uNmAnNeR/imaskjs#190] opened 2019-06-04 09:31 UTC
Hi, first of all, thank you for your great Plugin.
I am currently using in vue, and i try to use imask as Directive.

I have a problem here when I'm using props to bind the value into child component through directives, when it have an initial value from props, an input in children component, didn't mask automatically.
![image](https://user-images.githubusercontent.com/40293359/58862951-01a49080-86dc-11e9-85f1-070d68e82d8c.png)

if i edit the input, the mask appear again, but give a warning in console
![image](https://user-images.githubusercontent.com/40293359/58866679-41bb4180-86e3-11e9-908d-de21d7477229.png)

can i make an input automatically with masked value, when i'm passing initial value in props ?
or maybe something wrong with my code that make it the behaviour to be like that ?

and here is my code :

```
<template>
<b-form-group
        label-cols-sm="4"
        label-cols-lg="4"
        v-for="(v, index) in formContent"
        :key="index"
        :label="v.label"
        :label-for="v.name"
      >
        <b-form-input
          v-if="v.type === 'currency'"
          type="text"
          :id="v.name"
          :name="v.name"
          :value="v.value"
          v-imask="mask.amount"
          @accept="onAccept($event,index)"
        />
</b-form-group>
</template>
<script>
import { IMaskDirective } from "vue-imask";

export default {
  components: { },
  directives: {
    imask: IMaskDirective
  },
  props: {
    formContent: {
      required: true
    }
  },
  data() {
    return {
      mask: {
        amount: {
          mask: Number,
          scale: 2, 
          signed: false,
          thousandsSeparator: ",", 
          padFractionalZeros: false, 
          normalizeZeros: true,
          radix: ",", 
          mapToRadix: ["."], 
          max: 100000000
        },
             }
    };
  },
methods: {
    onAccept(e, index) {
      const maskRef = e.detail;
      this.$emit(
        "unmaskValueChanged",
        maskRef.value,
        maskRef.unmaskedValue,
        index
      );
    }
  }
};
</script>

```

Thank You, really looking forward for anyone can help..

**Comment by uNmAnNeR** [comment] 2019-06-05 07:47
seems that you use custom input `b-form-input` and directive may be incompatible since you might forget to pass all stuff from native input and vice versa. Check if all handlers of directive are connected properly.
May be someone Vue-expert will help more.

**Comment by Solant** [comment] 2019-06-06 14:55
Tried to reproduce your example: https://codesandbox.io/embed/vue-directive-element-value-was-changed-outside-of-mask-5xexm

imask should be fine with bootstrap component

Looks like you have an issue due to `props` mutation (changes are applied to field that is passed as prop), which is not recommended by Vue docs. You should store it in `data` section or use `Vuex`, if you need to pass it deeply into component tree

**Comment by yudhy101** [comment] 2019-06-09 17:22
Hi @Solant , thank you for reproduce my code into codesandbox. 

So far i'm learning  about vue, that `props` should not mutate directly in children component, that's why i use  `$emit` @onAccept event to mutate the `props` through `data` in parent component, so it will keep the one-way data flow.

or am i misunderstand about that ? pls correct me if i'm wrong, i'm still new.

btw i will try using Vuex..

**Comment by Solant** [comment] 2019-06-10 12:03
@yudhy101 yep, that's right. `$emit` is the intended way of passing events from child to parent, that has ownership of data, however, it can become messy in no time, so pay attention to the data flow.

@uNmAnNeR @yudhy101 looks like `imask` works fine in that case, can we close this issue?

**Comment by uNmAnNeR** [comment] 2019-06-14 06:18
@yudhy101  feel free to reopen
@Solant thanks a lot for support

**Closed by uNmAnNeR** 2019-06-14 06:18 UTC
