### ISSUE TITLE
I cannot type any seperators

### ISSUE THREAD

**Issue by SemmelJochen** [uNmAnNeR/imaskjs#297] opened 2020-02-07 13:18 UTC
Hi I have experienced a little bug.
I want to have a mask that imports a value of a defined field when double clicking on it and be able to edit the value.
Example values are: "304.434.343,24€" (dependent on locale it renders different grouping and decimal seperatos).
When a field has a value I can double click and edit the value. The problem is, if the value has decimals I can edit them as long I do not delete them. But if I try to manually enter a decimal I can't, because I can't enter the radix.
When I create a new field with no pre-filled values I also can't place the radix and therefore no decimals.

Another problem that occurs is when I copy a formatted string e.G. "4.000.000,00€" and try to paste it, the string will be cutted at the first thousands Seperator altought it is defined as one. So the pasted value will be "4,00€".

I hope you can understand what I mean since my english is not perfect and help me.

```javascript
        this.myRef = React.createRef();
        let mask;
        switch(this.locale){
            case "de-DE":
                mask = "num €";
                break;
            case "de-CH":
                mask = "EUR num";
                break;
            case "en-GB":
                mask = "€num";
                break;
            default:
                mask = "num €";
                break;
        }
        this.masks = {
            currencyDE: [
                {
                    mask: mask,
                    lazy: false,
                    //unmask: "typed",
                    blocks: {
                        num: {
                            mask: Number,
                            scale: validSeperators.getMaxFractionDigits(), //returns 2
                            thousandsSeparator: validSeperators.getGrouping(), //returns "." 
                            radix: validSeperators.getDecimal(), //returns ","
                            normalizeZeros: false,
                            padFractionalZeros: false,
                            mapToRadix: [validSeperators.getDecimal()]  //returns ","
                        }
                    }
                }
            ]
        };





      //in my render method
      <IMaskInput
          inputRef={el => this.myRef.current = el}
          value={this.state.rawValue} //e.G. "50.000.000,00 €"
          mask={this.masks.currencyDE}
          onAccept={value => this.handleChange(value)}
          style={{width: "80%"}}
      />

**Comment by uNmAnNeR** [comment] 2020-02-10 09:48
seems like a bug. thanks for reporting

**Comment by lunaboona** [comment] 2020-04-23 11:41
@uNmAnNeR Is there a fix for this planned?

**Closed** 2020-05-22 13:55 UTC
Labels: bug

**Comment by silveoj** [comment] 2021-02-08 16:53
@uNmAnNeR 
Thanks for `imask`.

1. It seems I found similar issue with `mapToRadix`.
https://stackblitz.com/edit/angular-imask-array-issue-hbzvcm?file=src/app/app.component.ts

```
  radix: '.',
  mapToRadix: [','],
```
If you paste value (which contains symbols from `mapToRadix`) it will be cutted: `91,234.88` --> ` 91.23`
(I noticed if I click button in example second time I will see correct value)

I can delete `mapToRadix` to avoid it. But I wouldn't like to remove this functionality.
So I use `mapToRadix` and `prepare` method:
```
  prepare: (val: string) => {
    return val.replace(',', '');
  },
  //...
  mapToRadix: [','],
```
Is it issue or by design?

Related https://github.com/uNmAnNeR/imaskjs/issues/186

2. Is there possibility and correct (imask) way to set default value if input is empty?
I use
```
    myInputControl.valueChanges.pipe(/* takeUntil */).subscribe((val) => {
      if (!val) {
        input2Control.setValue("0", { emitEvent: false });
      }
    });
```

3. About example https://imask.js.org/guide.html#masked-base
```
masked._value = value.toLowerCase();  // Don't do it
```
But how to do it correctly? I suggest you to improve doc for this point.

Thanks.
