### ISSUE TITLE
IMaskInput type not working properly "Typescript"

### ISSUE THREAD

**Issue by pilouk** [uNmAnNeR/imaskjs#554] opened 2021-09-24 12:33 UTC
**Describe the bug**
IMaskInput is not typed properly and result with this typing -> **_const IMaskInput: React.ComponentType<{}>_** 
IMaskInput is not taking any props like mask,definitions etc. and make it not usable with typescript at all (_Atleast the way i'm configured_).
![image](https://user-images.githubusercontent.com/1840762/134674373-36f86f3f-47e1-473f-ae33-0c924f770399.png)

Is there something I'm missing ?

**To Reproduce**
I have typescript 4.4.3, React 17.0.2 with Imask 6.2.2

**Environment:**
 - OS: Windows
 - Browser Chrome
 - IMask 6.2.2
 -  typescript 4.4.3, React 17.0.2

**Comment by momasz** [comment] 2021-09-24 17:41
I am experiencing the same issue

**Comment by hoangtrung99** [comment] 2021-09-24 18:28
I'm getting the same error and don't know how to handle it yet.

**Comment by dylancrockett** [comment] 2021-09-25 00:31
I am also having the same issue, will update if I can come up with a fix other than just using `//@ts-ignore` on each line.

**Comment by alb7h** [comment] 2021-09-28 09:14
Pretty certain it's because the return type on `IMaskMixin` overwrites the incoming types. So it goes through all the effort of bringing in a typed component, just to return a blank `React.ComponentType`.


https://github.com/uNmAnNeR/imaskjs/blob/2c5dad60d62d21614b895138c6c0369219ab88a4/packages/react-imask/src/mixin.ts#L108-L114

On compile, I think typescript notices this and simplifies the compiled types for anything wrapped with `IMaskMixin` to the following output 

```ts
import React from 'react';
declare const IMaskInput: React.ComponentType<{}>;
export default IMaskInput;
```

**Comment by lgberro** [comment] 2021-09-29 15:10
Downgrading to 6.1.0 solves while it is not solved.

**Comment by benkburke** [comment] 2021-11-12 15:23
Having this issue as well.  Downgrading did not work for me because types are not available in 6.1.0.  We are also not allowed to use ts-ignore, therefore adding `//@ts-expect-error` with a description solves the issue for now.  Looking forward to an update / fix.

**Comment by ReschAndr** [comment] 2021-12-01 10:14
Any updates on when this will be fixed?

**Comment by mcatal** [comment] 2021-12-10 06:31
Any suggestion ?

**Comment by romelgomez** [comment] 2021-12-13 16:01
@mcatal 

I add a this temp fix to pass the build: 

```
// @ts-ignore: hot fix for https://github.com/uNmAnNeR/imaskjs/issues/554
import { IMaskInput } from 'react-imask';
```



error: 

```
Step #0: Type error: Could not find a declaration file for module 'react-imask'. '/app/node_modules/react-imask/dist/react-imask.js' implicitly has an 'any' type.
Step #0:   Try `npm i --save-dev @types/react-imask` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-imask';`
Step #0: 
```

**Comment by AndrewGulidov** [comment] 2021-12-23 10:23
To work properly with typescript I found that the path to `index.d.ts` should be added in `types` property in package.json file. I guess it could fix issues with typescript.
Now it is missed here: https://github.com/uNmAnNeR/imaskjs/blob/master/packages/react-imask/package.json

Documentation:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by gynekolog** [comment] 2021-12-23 11:54
There exist a pull request that can close this issue -> https://github.com/uNmAnNeR/imaskjs/pull/576

**Comment by JonKrone** [comment] 2022-01-04 05:20
While that PR is in the wings, there is a change you can make to `typeRoots` in your `tsconfig.json` file to tell Typescript where these type files are within react-imask. https://www.typescriptlang.org/tsconfig#typeRoots

```jsonc
"compilerOptions": {
  ...,
  // If you don't already use this config option, you'll need to explicitly add your node_module/@types folders
 "typeRoots": [
   "./node_modules/@types",
   "../../node_modules/@types", // If you're in a workspace, you may have a hoisted @types.
   /**
    *  react-imask has types but does not specify where they are in the package.json file.
    *  @see https://github.com/uNmAnNeR/imaskjs/pull/576
    */
   "../../node_modules/react-imask/dist/index.d.ts",
 ],
}

```

**Comment by xzessmedia** [comment] 2022-01-19 10:37
Since none of the provided solutions here worked for me,
my quick and dirty workaround is to change the types of the component to any

For using IMaskMixing, (React.ComponentType<any> in the last line in mixing.d.ts):
`export default function IMaskMixin<Opts extends IMask.AnyMaskedOptions = IMask.AnyMaskedOptions, Unmask extends ('typed' | boolean) = false, Value = Unmask extends 'typed' ? IMask.InputMask<Opts>['typedValue'] : Unmask extends Falsy ? IMask.InputMask<Opts>['value'] : IMask.InputMask<Opts>['unmaskedValue']>(ComposedComponent: React.ComponentType<IMaskMixinProps<Opts, Unmask, Value>>): React.ComponentType<any>;`

For using IMaskInput replace in input.d.ts):
`import React from 'react';
declare const IMaskInput: React.ComponentType<any>;
export default IMaskInput;
`

**Closed** 2022-01-25 12:28 UTC

**Comment by RyKilleen** [comment] 2022-04-30 16:17
It appears it's not possible to pass `unmask` to `IMaskMixin` without type errors. Is this by design or an accident?

**Comment by itsclarke** [comment] 2022-05-05 18:25
> @uNmAnNeR It appears it's not possible to pass `unmask` to `IMaskMixin` without type errors. Is this by design or an accident?
> 
> Happy to open another issue as relevant.
> 
> ![image](https://user-images.githubusercontent.com/4615840/166113656-fdbe382e-4cdf-4c85-b923-d0b811d101e9.png)

I'm also experiencing this issue

**Comment by kumold** [comment] 2022-05-20 06:36
> > @uNmAnNeR It appears it's not possible to pass `unmask` to `IMaskMixin` without type errors. Is this by design or an accident?
> > Happy to open another issue as relevant.
> > ![image](https://user-images.githubusercontent.com/4615840/166113656-fdbe382e-4cdf-4c85-b923-d0b811d101e9.png)
> 
> I'm also experiencing this issue

Same here. Any workarounds?

**Comment by maganezf** [comment] 2024-03-13 21:05
I'm using hook-form and `react-imask`, and it was solved using these versions:

```
"react-hook-form": "^7.51.0",
"react-imask": "7.1.3"
```
